-- Luna MR-A: advisory/shadow meeting-room backend
-- Additive only. No trading/runtime parameter path consumes these tables.

CREATE SCHEMA IF NOT EXISTS investment;

CREATE TABLE IF NOT EXISTS investment.luna_meeting_sessions (
  id         BIGSERIAL PRIMARY KEY,
  type       TEXT NOT NULL CHECK (type IN ('morning', 'domestic_debrief', 'us_premarket', 'weekly', 'adhoc')),
  status     TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
  chair      TEXT NOT NULL DEFAULT 'luna' CHECK (chair IN ('master', 'luna')),
  segments   JSONB NOT NULL DEFAULT '[]'::jsonb,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  closed_at  TIMESTAMPTZ,
  summary    TEXT
);

CREATE TABLE IF NOT EXISTS investment.luna_meeting_minutes (
  id         BIGSERIAL PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES investment.luna_meeting_sessions(id) ON DELETE CASCADE,
  seq        INTEGER NOT NULL,
  agenda_key TEXT NOT NULL,
  speaker    TEXT NOT NULL,
  role       TEXT NOT NULL CHECK (role IN ('data', 'analysis', 'grill', 'decision', 'system')),
  content    TEXT NOT NULL,
  meta       JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (session_id, seq)
);

CREATE TABLE IF NOT EXISTS investment.luna_meeting_decisions (
  id         BIGSERIAL PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES investment.luna_meeting_sessions(id) ON DELETE CASCADE,
  agenda_key TEXT NOT NULL,
  decision   TEXT NOT NULL,
  grade      TEXT NOT NULL CHECK (grade IN ('a_rule', 'b_boundary', 'c_master')),
  status     TEXT NOT NULL DEFAULT 'advisory' CHECK (status IN ('advisory', 'pending_master', 'confirmed', 'deferred')),
  due_at     TIMESTAMPTZ,
  evidence   JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_luna_meeting_sessions_type_started
  ON investment.luna_meeting_sessions(type, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_luna_meeting_minutes_session_seq
  ON investment.luna_meeting_minutes(session_id, seq);

CREATE INDEX IF NOT EXISTS idx_luna_meeting_decisions_session_agenda
  ON investment.luna_meeting_decisions(session_id, agenda_key);

CREATE INDEX IF NOT EXISTS idx_luna_meeting_decisions_status_due
  ON investment.luna_meeting_decisions(status, due_at);

COMMENT ON TABLE investment.luna_meeting_sessions IS
  'Luna meeting-room advisory/shadow sessions. Trading and runtime parameter paths do not consume this table.';

COMMENT ON TABLE investment.luna_meeting_minutes IS
  'Luna meeting-room transcript/minutes rows generated by CLI/FSM orchestration.';

COMMENT ON TABLE investment.luna_meeting_decisions IS
  'Luna meeting-room ADR rows. MR-A records advisory decisions only.';
