#!/usr/bin/env tsx
// @ts-nocheck

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = process.env.PROJECT_ROOT || path.resolve(SCRIPT_DIR, '..', '..', '..');
const DEFAULT_SNAPSHOT_PATH = path.join(PROJECT_ROOT, 'docs', 'hub', 'snapshots', 'llm-chain-snapshot-2026-06-12.json');
const DEFAULT_OUTPUT_PATH = path.join(PROJECT_ROOT, 'packages', 'core', 'lib', 'llm-policy-table.ts');

function parseArgs(argv = process.argv.slice(2)) {
  const args = {
    check: false,
    json: false,
    snapshotPath: DEFAULT_SNAPSHOT_PATH,
    outputPath: DEFAULT_OUTPUT_PATH,
  };
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--check') args.check = true;
    else if (arg === '--json') args.json = true;
    else if (arg === '--snapshot') args.snapshotPath = path.resolve(argv[++index] || '');
    else if (arg.startsWith('--snapshot=')) args.snapshotPath = path.resolve(arg.slice('--snapshot='.length));
    else if (arg === '--out') args.outputPath = path.resolve(argv[++index] || '');
    else if (arg.startsWith('--out=')) args.outputPath = path.resolve(arg.slice('--out='.length));
    else throw new Error(`unknown argument: ${arg}`);
  }
  return args;
}

function clean(value) {
  return String(value || '').trim();
}

function slug(value) {
  return clean(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'default';
}

function teamFromSelectorKey(selectorKey) {
  return clean(selectorKey).split('.')[0] || '*';
}

function normalizeChainEntry(entry = {}) {
  const row = {
    provider: clean(entry.provider),
    model: clean(entry.model),
  };
  const maxTokens = Number(entry.maxTokens);
  const temperature = Number(entry.temperature);
  const timeoutMs = Number(entry.timeoutMs);
  if (Number.isFinite(maxTokens)) row.maxTokens = maxTokens;
  if (Number.isFinite(temperature)) row.temperature = temperature;
  if (Number.isFinite(timeoutMs)) row.timeoutMs = timeoutMs;
  return row;
}

function ruleFromSnapshotRow(row) {
  const selectorKey = clean(row.key);
  const agent = clean(row.agentName);
  const taskType = clean(row.taskType || row.runtimePurpose);
  const variant = clean(row.variant) || 'default';
  const match = {
    team: teamFromSelectorKey(selectorKey),
    selectorKey,
  };
  if (agent) match.agent = agent;
  if (taskType) match.taskType = taskType;
  return {
    id: [selectorKey, agent || 'default', variant].map(slug).join('__'),
    match,
    chain: (Array.isArray(row.chain) ? row.chain : []).map(normalizeChainEntry),
  };
}

function sortRule(a, b) {
  const aKey = [
    a.match.selectorKey || '',
    a.match.agent || '',
    a.match.taskType || '',
    a.id,
  ].join('\u0000');
  const bKey = [
    b.match.selectorKey || '',
    b.match.agent || '',
    b.match.taskType || '',
    b.id,
  ].join('\u0000');
  return aKey.localeCompare(bKey);
}

function stableStringify(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function buildPolicyTableSource(snapshot, snapshotPath = DEFAULT_SNAPSHOT_PATH) {
  const rules = (Array.isArray(snapshot?.variants) ? snapshot.variants : [])
    .filter((row) => !row.error)
    .map(ruleFromSnapshotRow)
    .sort(sortRule);
  const generatedFrom = path.relative(PROJECT_ROOT, snapshotPath);
  return [
    '// @ts-nocheck',
    '// Generated by bots/hub/scripts/llm-policy-table-codegen.ts.',
    '// Do not edit by hand; update the R1 snapshot or codegen and regenerate.',
    '',
    'export type PolicyChainEntry = string | {',
    '  provider: string;',
    '  model: string;',
    '  maxTokens?: number;',
    '  temperature?: number;',
    '  timeoutMs?: number;',
    '};',
    '',
    'export type PolicyRule = {',
    '  id: string;',
    '  match: { team: string; selectorKey?: string; agent?: string; taskType?: string };',
    '  chain: PolicyChainEntry[];',
    '  caps?: { maxTokens?: number; temperature?: number };',
    '};',
    '',
    `export const LLM_POLICY_TABLE_GENERATED_FROM = ${JSON.stringify(generatedFrom)};`,
    `export const LLM_POLICY_TABLE_GENERATED_AT = ${JSON.stringify(snapshot?.generatedAt || null)};`,
    `export const LLM_POLICY_TABLE_SELECTOR_VERSION = ${JSON.stringify(snapshot?.selectorVersion || null)};`,
    `export const LLM_POLICY_TABLE_RULE_COUNT = ${rules.length};`,
    '',
    `export const LLM_POLICY_RULES: PolicyRule[] = ${stableStringify(rules).trim()};`,
    '',
  ].join('\n');
}

function buildReport(args, changed, ruleCount) {
  return {
    ok: !args.check || !changed,
    changed,
    check: args.check,
    snapshotPath: path.relative(PROJECT_ROOT, args.snapshotPath),
    outputPath: path.relative(PROJECT_ROOT, args.outputPath),
    ruleCount,
  };
}

async function main() {
  const args = parseArgs();
  const snapshot = JSON.parse(fs.readFileSync(args.snapshotPath, 'utf8'));
  const source = buildPolicyTableSource(snapshot, args.snapshotPath);
  const current = fs.existsSync(args.outputPath) ? fs.readFileSync(args.outputPath, 'utf8') : '';
  const changed = current !== source;
  const ruleCount = (source.match(/"id":/g) || []).length;
  const report = buildReport(args, changed, ruleCount);

  if (args.check) {
    if (args.json) console.log(JSON.stringify(report, null, 2));
    else console.log(`[llm-policy-table-codegen] check changed=${changed} rules=${ruleCount}`);
    process.exitCode = changed ? 1 : 0;
    return;
  }

  fs.mkdirSync(path.dirname(args.outputPath), { recursive: true });
  fs.writeFileSync(args.outputPath, source);
  if (args.json) console.log(JSON.stringify(report, null, 2));
  else console.log(`[llm-policy-table-codegen] wrote ${path.relative(PROJECT_ROOT, args.outputPath)} rules=${ruleCount}`);
}

main().catch((error) => {
  console.error(error?.stack || error?.message || error);
  process.exitCode = 1;
});
