-- Copy this file into the owning bot's migrations directory, then replace both
-- placeholders. New persistent tables must be schema-qualified and must retain
-- the role grant section below. Do not grant DML, ALL, ownership, or sequences to
-- hub_readonly. Migration execution remains a separate master-approved action.

BEGIN;

CREATE TABLE IF NOT EXISTS __SCHEMA__.__TABLE__ (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Required read-only role grants. Explicit grants remain mandatory because
-- PostgreSQL default privileges are owner-specific and do not grant schema USAGE.
GRANT USAGE ON SCHEMA __SCHEMA__ TO hub_readonly;
GRANT SELECT ON TABLE __SCHEMA__.__TABLE__ TO hub_readonly;

COMMIT;
